// archive/maxed-marketing-visual-explorer/App.tsx
import React, { useState } from 'react';
import { Sidebar } from './components/Sidebar';
import { Dashboard } from './components/Dashboard';
import { ThemeSwitcher } from './components/ThemeSwitcher';
import { Theme, View } from './types';

function App() {
  const [theme, setTheme] = useState<Theme>('focus');
  const [currentView, setCurrentView] = useState<View>('dashboard');

  return (
    <div className="flex h-screen w-full transition-theme overflow-hidden bg-amplify-dark">
      <Sidebar 
        theme={theme} 
        currentView={currentView} 
        setView={setCurrentView} 
      />
      {/* Dashboard component handles routing internally based on currentView */}
      <Dashboard 
        theme={theme} 
        currentView={currentView}
        setView={setCurrentView}
      />
      <ThemeSwitcher currentTheme={theme} setTheme={setTheme} />
    </div>
  );
}

export default App;

// src/client/src/App.vue
<script setup lang="ts">
import { useRoute, RouterView } from 'vue-router';
import Sidebar from './components/Sidebar.vue';
import HeaderBar from './components/HeaderBar.vue';

const route = useRoute();
</script>

<template>
  <div class="flex h-screen w-full transition-theme overflow-hidden bg-amplify-dark">
    <Sidebar />
    <div class="flex-1 flex flex-col h-full overflow-hidden bg-stone-50">
      <HeaderBar :route-name="route.name?.toString() || ''" />
      <main class="flex-1 overflow-hidden relative">
        <RouterView v-slot="{ Component }">
          <component :is="Component" />
        </RouterView>
      </main>
    </div>
  </div>
</template>
