// src/client/src/components/Sidebar.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router';
import { LayoutDashboard, BarChart3, Sparkles, MapPin, Settings, ChevronRight, Lock, MessageSquare, HelpCircle } from 'lucide-vue-next';
const router = useRouter();
const route = useRoute();

const navItems = [
  { id: 'dashboard', icon: LayoutDashboard, label: 'Dashboard', path: '/' },
  { id: 'brand-voice', icon: MessageSquare, label: 'Brand Voice Tracker', path: '/brand-voice' },
  { id: 'google-ads', icon: BarChart3, label: 'Google Ads Suite', path: '/google-ads' },
  { id: 'social-spark', icon: Sparkles, label: 'Social Spark', path: '/social-spark' },
  { id: 'local-seo', icon: MapPin, label: 'Local SEO', path: '/local-seo', locked: true },
  { id: 'settings', icon: Settings, label: 'Settings', path: '/settings' }
];

const setView = (item: typeof navItems[number]) => {
  if (item.locked) return;
  router.push(item.path);
};

const isActive = (itemId: string) => route.name === itemId;
</script>

<template>
  <aside class="w-64 bg-amplify-dark border-r border-slate-800 flex flex-col h-full transition-theme flex-shrink-0 z-20">
    <div class="p-6">
      <div class="flex items-center gap-3">
        <div class="w-8 h-8 bg-amplify-green rounded-lg flex items-center justify-center text-amplify-darker font-bold text-xl relative overflow-hidden">
          <span class="z-10">M</span>
          <div class="absolute top-0 right-0 w-4 h-4 bg-white/30 rounded-bl-lg" />
        </div>
        <div>
          <h1 class="text-lg font-bold text-white tracking-tight leading-none">MAXED</h1>
          <p class="text-[10px] text-amplify-green font-mono tracking-widest uppercase">Marketing.OS</p>
        </div>
      </div>
    </div>

    <nav class="flex-1 px-3 space-y-1 mt-4">
      <div class="px-3 mb-2 text-xs font-semibold text-slate-500 uppercase tracking-wider">Apps</div>
      <div
        v-for="item in navItems"
        :key="item.id"
        @click="() => setView(item)"
        class="flex items-center justify-between px-3 py-3 rounded-xl transition-all cursor-pointer group relative"
        :class="[
          isActive(item.id)
            ? 'bg-slate-800 text-amplify-green border border-slate-700'
            : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200 border border-transparent',
          item.locked ? 'opacity-50 cursor-not-allowed' : ''
        ]"
      >
        <div class="flex items-center gap-3">
          <component
            :is="item.icon"
            :size="20"
            class="transition-colors"
            :class="isActive(item.id) ? 'text-amplify-green' : 'text-slate-500 group-hover:text-slate-300'"
          />
          <span class="text-sm" :class="isActive(item.id) ? 'font-bold' : 'font-medium'">{{ item.label }}</span>
        </div>
        <ChevronRight v-if="isActive(item.id)" :size="14" class="text-amplify-green" />
        <Lock v-if="item.locked" :size="12" class="text-slate-600" />
      </div>
    </nav>

    <div class="p-4">
      <div class="bg-gradient-to-br from-slate-800 to-slate-900 p-4 rounded-2xl border border-slate-700">
        <div class="flex items-center gap-2 text-amplify-green mb-2">
          <HelpCircle :size="18" />
          <span class="font-bold text-sm">Need a hand?</span>
        </div>
        <p class="text-xs text-slate-400 mb-3">Our marketing guides are here to support your growth.</p>
        <button class="w-full bg-amplify-green py-2 rounded-lg text-xs font-bold text-amplify-darker hover:bg-white transition-colors">
          Open Guide
        </button>
      </div>
    </div>
  </aside>
</template>

// archive/google-ads-suite/components/Sidebar.tsx
import React from 'react';
import { LayoutDashboard, BarChart3, Sparkles, MapPin, Settings, Lock, X } from 'lucide-react';
import { AppView } from '../types';
import { motion } from 'framer-motion';

interface SidebarProps {
  currentView: AppView;
  onChangeView: (view: AppView) => void;
  onLockedItemClick: (viewId: AppView, label: string) => void;
  unlockedItems: AppView[];
  className?: string;
  onClose?: () => void;
}

export const Sidebar: React.FC<SidebarProps> = ({ 
  currentView, 
  onChangeView, 
  onLockedItemClick, 
  unlockedItems = [], 
  className = '',
  onClose
}) => {
  
  const getIcon = (iconName: string, className: string) => {
    switch (iconName) {
      case 'LayoutDashboard': return <LayoutDashboard className={className} />;
      case 'BarChart3': return <BarChart3 className={className} />;
      case 'Sparkles': return <Sparkles className={className} />;
      case 'MapPin': return <MapPin className={className} />;
      case 'Settings': return <Settings className={className} />;
      default: return null;
    }
  };

  const navItems = [
    { id: AppView.DASHBOARD, label: 'Dashboard', icon: 'LayoutDashboard', locked: false },
    { id: AppView.GOOGLE_ADS, label: 'Google Ads Suite', icon: 'BarChart3', locked: false },
    { id: AppView.SOCIAL_SPARK, label: 'Social Spark', icon: 'Sparkles', locked: true },
    { id: AppView.LOCAL_SEO, label: 'Local SEO', icon: 'MapPin', locked: true },
    { id: AppView.SETTINGS, label: 'Settings', icon: 'Settings', locked: false },
  ];

  return (
    <aside className={`flex flex-col h-full bg-slate-900 text-slate-300 ${className}`}>
      {/* Brand Header */}
      <div className="h-16 flex items-center justify-between px-6 border-b border-slate-800 bg-slate-950 flex-shrink-0">
        <div className="flex items-center">
            <div className="w-8 h-8 bg-orange-500 rounded-lg flex items-center justify-center mr-3">
                <span className="text-white font-bold text-lg">M</span>
            </div>
            <span className="font-bold text-white tracking-tight">Maxed Marketing</span>
        </div>
        {/* Mobile Close Button */}
        <button 
            onClick={onClose}
            className="md:hidden text-slate-400 hover:text-white transition-colors p-1"
        >
            <X className="w-6 h-6" />
        </button>
      </div>

      {/* Navigation */}
      <nav className="flex-1 px-3 py-6 space-y-1 overflow-y-auto">
        {navItems.map((item) => {
          const isActive = currentView === item.id;
          // Item is effectively locked only if it's marked locked AND not in the unlockedItems list
          const isLocked = item.locked && !unlockedItems.includes(item.id);

          return (
            <button
              key={item.id}
              onClick={() => {
                  if (isLocked) {
                      onLockedItemClick(item.id, item.label);
                  } else {
                      onChangeView(item.id);
                      if (onClose) onClose(); // Close sidebar on mobile selection
                  }
              }}
              className={`
                group flex items-center w-full px-3 py-3 text-sm font-medium rounded-md transition-all duration-200 relative
                ${isActive 
                  ? 'bg-indigo-600 text-white shadow-md' 
                  : 'hover:bg-slate-800 text-slate-400 hover:text-white'
                }
              `}
            >
              {getIcon(item.icon, `mr-3 h-5 w-5 ${isActive ? 'text-white' : 'text-slate-400 group-hover:text-white'}`)}
              <span className="flex-1 text-left flex items-center justify-between">
                {item.label}
                {isLocked && <Lock className="h-3 w-3 text-slate-600 group-hover:text-slate-500" />}
              </span>
              
              {isActive && (
                <motion.div 
                  layoutId="activeIndicator"
                  className="absolute left-0 w-1 h-8 bg-orange-400 rounded-r-full"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.2 }}
                />
              )}
            </button>
          );
        })}
      </nav>

      {/* User Profile Footer */}
      <div className="p-4 border-t border-slate-800 bg-slate-950/50 flex-shrink-0">
        <div className="flex items-center">
          <div className="h-9 w-9 rounded-full bg-indigo-500 flex items-center justify-center text-white font-bold shadow-sm">
            GM
          </div>
          <div className="ml-3">
            <p className="text-sm font-medium text-white">George's Music</p>
            <p className="text-xs text-slate-500">Premium Plan</p>
          </div>
        </div>
      </div>
    </aside>
  );
};
